language: cpp

sudo: required
dist: trusty

before_install:
  - travis_retry sudo add-apt-repository -y ppa:hvr/ghc
  - travis_retry sudo apt-get update
  - travis_retry sudo apt-get -y install libtokyocabinet-dev
  - travis_retry sudo apt-get -y install libboost-program-options-dev libboost-regex-dev libboost-serialization-dev libboost-thread-dev
  - travis_retry sudo apt-get -y install uuid-dev
  - travis_retry sudo apt-get -y install git
  - travis_retry sudo apt-get -y install cabal-install-1.18 ghc-7.6.3
  - travis_retry sudo apt-get -y install git
  - export PATH=$HOME/.cabal/bin:/opt/ghc/7.6.3/bin:/opt/cabal/1.18/bin:$PATH
  - git clone https://github.com/gree/flare.git
  - cabal update

script:
  - cabal install
  - (cd flare && ./autogen.sh && ./configure && make && sudo make install)
  - flare-tests
  - for i in *.txt ; do echo --- "$i"  --- ; cat "$i" ;done
  - sudo cat /var/log/syslog
