language: haskell

before_install:
  - travis_retry sudo apt-get update
  - travis_retry sudo apt-get install libtokyocabinet-dev
  - travis_retry sudo apt-get install libboost-program-options-dev libboost-regex-dev libboost-serialization-dev libboost-thread-dev
  - travis_retry sudo apt-get install uuid-dev
  - travis_retry sudo apt-get install git
  - git clone https://github.com/gree/flare.git
  - cabal update

script:
  - cabal install
  - (cd flare && ./autogen.sh && ./configure && make && sudo make install)
  - flare-tests

